spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dbgirl?characterEncoding=utf-8&useSSL=false
    username: peng
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create
    show-sql: true
